### ISSUE TITLE
1.20.1 port?

### ISSUE THREAD

**Issue by lostopkk** [dooji2/server-notify#1]
i like the mod but is 1.19.2 and my modpack is 1.20.1, are you planning support 1.20.1?

**Comment by dooji2** [comment]
Hey there!

~~I hope the modpack is for multiplayer usage as this mod shouldn't really be used in singleplayer since it doesn't really work properly lol~~. Might fix it at some point but yeah.

Anyway, yep I am! I'm planning support for 1.18.2, 1.19.4, 1.20.1, and 1.20.4 for now. Haven't started porting to other versions yet though, would prefer to polish the mod first before doing so.

Update: 1.20.1 is now supported!
